---
title: "Outputs"
format: html
---

# Load Data
```{r}
#|echo: false

GSE143791_Seurat_Object = readRDS(file = "/Users/david/Documents/Single_Cell_Datasets/Prostate/GSE143791/data/GSE143791_Seurat_Object.RDS")


```

# Genes of interest
```{r}

genes_of_interest = c("AXL", "TYRO3", "MERTK", "GAS6")
#FLT3 not in dataset

```


# Clusters
```{r}

Seurat::DimPlot(GSE143791_Seurat_Object, label = TRUE) + Seurat::NoLegend()
Seurat::DimPlot(GSE143791_Seurat_Object, label = TRUE, split.by = "Location") + Seurat::NoLegend()

```

# Cell Type Labels
```{r}

Seurat::DimPlot(GSE143791_Seurat_Object, label = TRUE, group.by = "Cell_Type") + Seurat::NoLegend()
Seurat::DimPlot(GSE143791_Seurat_Object, label = TRUE, group.by = "Cell_Type", split.by = "Location") + Seurat::NoLegend()

```
# TAM Expression

## Seurat Plots
```{r}

lapply(genes_of_interest, Seurat::FeaturePlot, object = GSE143791_Seurat_Object, split.by = "Location")


```

# Dot Plot


## schex Plots
```{r}

for(gene in genes_of_interest){
  print(schex::plot_hexbin_gene(GSE143791_Seurat_Object, type = "SCT", gene = gene, action = "prop_0", title = gene))
}

rm(gene)

```


# Dot Plots
```{r}

Seurat::DotPlot(GSE143791_Seurat_Object, features = genes_of_interest, group.by = "Cell_Type", cols = c("white", "red")) + 
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90)) +
  ggplot2::ggtitle("Prostate (Bone Mets) - GSE143791")

rm(genes_of_interest)

```